# netlify.toml - Netlify configuration file

[build]
  # Base directory relative to repository root
  base = "Front-End"

  # Build command executed *within* the base directory
  command = "npm run build"

  # Publish directory relative to the *base* directory
  # Or sometimes relative to the repository root if base is complex.
  # Let's try relative to base first, as is standard.
  publish = "dist"

# Redirect rule for Single Page Applications (React Router)
# This handles the 404 error on refresh/direct navigation
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 # Serve the index.html file without a redirect status