services:
  # Backend Service (Web Service)
  - type: web # Important: This defines the backend
    name: auroa-intel-back-end # Use the exact name of your backend service
    runtime: node
    region: oregon # Change to your chosen region (e.g., ohio)
    branch: master
    rootDir: Back-End
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://auroa-intel-front-end.onrender.com # Frontend URL for CORS
      # Add other backend envVars like DATABASE_URL, JWT_SECRET here
      # - key: DATABASE_URL
      #   sync: false # Set sync: false if you manage it only in the dashboard
      # - key: JWT_SECRET
      #   sync: false

  # Frontend Service (Static Site)
  - type: static # Important: This defines the frontend
    name: auroa-intel-front-end # Use the exact name of your frontend service
    region: oregon # Change to your chosen region (e.g., ohio)
    branch: master
    # Note: No rootDir needed if paths are relative to root in commands
    buildCommand: "cd Front-End && npm install && npm run build"
    publishDir: Front-End/dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://auroa-intel.onrender.com # Backend URL for frontend code
    routes:
      # Rewrite rule for SPA routing
      - type: rewrite
        source: /*
        destination: /index.html
